const prompts = [
    "What's the worst name for a robot?",
    'If animals could talk, which would be the rudest?',
    "What's invisible but you wish people could see?",
    "What's the weirdest thing you could say to a stranger on an elevator?",
    'If you could have an unlimited supply of one thing, what would it be?',
    "What's the most useless superhero power you can imagine?",
    "What would be the worst 'buy one get one free' sale of all time?",
    'If you could remove one color from the world, which would it be?',
    "What's something that everyone looks stupid doing?",
    'What would be the creepiest thing you could say to someone passing by on the street?',
    'If you were a ghost, where would you haunt and why?',
    "What's the most ridiculous fact you know?",
    'If you had to be haunted by a ghost, which celebrity would you choose?',
    "What's the best Wi-Fi name you've ever seen?",
    'If animals were as intelligent as humans, which species would be in charge?',
    'What would be the absolute worst name you could give your child?',
    'What is something that everyone agrees we should change, but somehow it never changes?',
    'What historical period would be the worst to be born in?',
    'If you could merge two animals to create the ultimate animal, what two animals would it be?',
    "What's the funniest word in the English language?",
    "What's the worst ingredient to fill a piñata with?",
    'If you could detach one body part and why?',
    'What is the most boring superpower you can think of?',
    'How would you survive a zombie apocalypse using only items in your kitchen?',
    'What would be the title of your autobiography?',
    'If you had to wear a costume every day for a year, what would it be?',
    'What would you name a boat if you had one?',
    "What's the funniest use for a time machine?",
    'If you could add a word to the dictionary, what would it be, and its definition?',
    "What's the most inconvenient thing to be allergic to?",
    'What would be the worst thing to hear as you are going under anesthesia before surgery?',
    "What's the most creative use of emojis you've ever seen?",
    'If you could only speak one word today, what would you say?',
    'What animal would be the most terrifying if it could speak?',
    'What is the worst pizza topping that has never been tried?',
    "What's the best type of cheese to build a house with?",
    'What movie title best describes your life?',
    'What is the most inappropriate thing to say at a wedding?',
    'If you could lock up one person in a mental institution, who would it be?',
    'If you had to replace your hands with something other than hands or claws, what would you choose?'
]

export default prompts
