const prompts = [
    "What's the worst name for a robot?",
    'If animals could talk, which would be the rudest?',
    "What's invisible but you wish people could see?",
    "What's the weirdest thing you could say to a stranger on an elevator?",
    'If you could have an unlimited supply of one thing, what would it be?',
    "What's the most useless superhero power you can imagine?",
    "What would be the worst 'buy one get one free' sale of all time?",
    'If you could remove one color from the world, which would it be?',
    "What's something that everyone looks stupid doing?",
    'What would be the creepiest thing you could say to someone passing by on the street?',
    'If you were a ghost, where would you haunt and why?',
    "What's the most ridiculous fact you know?",
    'If you had to be haunted by a ghost, which celebrity would you choose?',
    "What's the best Wi-Fi name you've ever seen?",
    'If animals were as intelligent as humans, which species would be in charge?',
    'What would be the absolute worst name you could give your child?',
    'What is something that everyone agrees we should change, but somehow it never changes?',
    'If you could merge two animals to create the ultimate animal, what two animals would it be?',
    "What's the funniest word in the English language?",
    "What's the worst ingredient to fill a piñata with?",
    'If you could detach one body part and why?',
    'What is the most boring superpower you can think of?',
    'How would you survive a zombie apocalypse using only items in your kitchen?',
    'What would be the title of your autobiography?',
    'If you had to wear a costume every day for a year, what would it be?',
    'What would you name a boat if you had one?',
    "What's the funniest use for a time machine?",
    'If you could add a word to the dictionary, what would it be, and its definition?',
    "What's the most inconvenient thing to be allergic to?",
    'What would be the worst thing to hear as you are going under anesthesia before surgery?',
    "What's the most ridiculous thing you've bought online?",
    'If you could only speak one word today, what would you say?',
    'What animal would be the most terrifying if it could speak?',
    'What is the worst pizza topping that has never been tried?',
    "What's the best type of cheese to build a house with?",
    'What movie title best describes your life?',
    'What is the most inappropriate thing to say at a wedding?',
    'If you could lock up one person in a mental institution, who would it be?',
    'If you had to replace your hands with something other than hands or claws, what would you choose?',
    "What secret conspiracy would you like to start?",
    "If you could replace all of the grass in the world with something else, what would it be?",
    "What's the most imaginative insult you can come up with?",
    "Which body part do you wish you could detach and why?",
    "What would be the worst thing to hear as you are going under anesthesia before heart surgery?",
    "What's the weirdest gift you've ever received?",
    "What would you do if you were the last person on Earth?",
    "What's the most ridiculous thing someone could have in their backyard?",
    "What fictional character would be the most boring to meet in real life?",
    "If you could have an extra body part, what would it be and why?",
    "What's something that's illegal but doesn't feel illegal?",
    "If animals could talk, which would be the sassiest?",
    "What's the weirdest smell you have ever smelled?",
    "If you could have dinner with any fictional villain, who would it be and why?",
    "What's the most useless gadget you've ever bought?",
    "If your life was a video game, what would some of the cheat codes be?",
    "What's the most unusual fear you have?",
    "If you could remove one thing from existence, what would it be?",
    "What's the weirdest thing you can do with a potato?",
    "If you had to be a character in a horror movie, which would you choose and why?",
    "What would you name a new planet and why?",
    "If you could turn any activity into an Olympic sport, what would you have a good chance at winning a medal for?",
    "What is the most hilarious corporate / business screw up you have heard of?",
    "What is something that you just recently realized that you are embarrassed you didn't realize earlier?",
    "What set of items could you buy that would make the cashier the most uncomfortable?",
    "What would be the creepiest thing you could say while passing a stranger on the street?",
    "If your job gave you a surprise three day paid break to rest and recuperate, what would you do with those three days?",
    "What's the most imaginative thing you've ever done?",
    "If you were famous, what would you be famous for?",
    "What TV show character would it be the most fun to change places with for a week?",
    "What's the most interesting building you've ever seen or been in?",
    "If you were transported 400 years into the past with no clothes or anything else, how would you prove that you were from the future?",
    "If you could talk to animals and they would understand, but you could never speak to humans again, would you do it?",
    "What's the best type of cheese to write a book about and why?",
    "What are some of the nicknames you have for customers or coworkers?",
    "If peanut butter wasn't called peanut butter, what would it be called?",
    "What movie would be greatly improved if it was made into a musical?",
    "What is the funniest corporate / business screw-up you have ever heard of?",
    "What would be the coolest animal to scale up to the size of a horse?",
    "What outdated slang do you use on a regular basis?"
]

export default prompts
